site_name: DayApp Documentation
site_description: Seu diário pessoal e seguro para registrar seus momentos especiais
nav:
  - Home: index.md  
  - Estratégia Completa: estrategia_completa.md
  - Plano de Publicação: PLANO_PUBLICACAO_DAYAPP_2026.md



  - About: about.md
  
#theme:
#  name: readthedocs

